// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

const { ActivityHandler, ActivityTypes } = require('botbuilder');

class HostBot extends ActivityHandler {
    constructor(dialog, conversationState, skillsConfig, skillClient) {
        super();
        if (!conversationState) throw new Error('[HostBot]: Missing parameter. conversationState is required');
        if (!skillsConfig) throw new Error('[HostBot]: Missing parameter. skillsConfig is required');
        if (!skillClient) throw new Error('[HostBot]: Missing parameter. skillClient is required');

        this.conversationState = conversationState;
        this.skillsConfig = skillsConfig;
        this.skillClient = skillClient;
        this.dialog = dialog;
        this.dialogState = this.conversationState.createProperty('DialogState');

        this.botId = process.env.MicrosoftAppId;
        if (!this.botId) {
            throw new Error('[HostBot] MicrosoftAppId is not set in configuration');
        }

        // Create state property to track the delivery mode and active skill.
        this.deliveryModeProperty = this.conversationState.createProperty(HostBot.DeliveryModePropertyName);
        this.activeSkillProperty = this.conversationState.createProperty(HostBot.ActiveSkillPropertyName);

        // See https://aka.ms/about-bot-activity-message to learn more about the message and other activity types.
        this.onMessage(async (context, next) => {
            // Try to get the active skill.
            const activeSkill = await this.activeSkillProperty.get(context);

            if (activeSkill) {
                // Send the activity to the skill
                await this.sendToSkill(context, activeSkill);
            } else {
                await this.dialog.run(context, this.dialogState);
            }

            // By calling next() you ensure that the next BotHandler is run.
            await next();
        });

        this.onEndOfConversation(async (context, next) => {
            // Handle EndOfConversation returned by the skill.
            if (context.activity.type === ActivityTypes.EndOfConversation) {
                // Forget delivery mode and skill invocation.
                await this.deliveryModeProperty.set(context, undefined);
                await this.activeSkillProperty.set(context, undefined);

                // Show status message, text and value returned by the skill.
                let eocActivityMessage = `Received ${ ActivityTypes.EndOfConversation }.\n\nCode: ${ context.activity.code }`;
                if (context.activity.text) {
                    eocActivityMessage += `\n\nText: ${ context.activity.text }`;
                }

                if (context.activity.value) {
                    eocActivityMessage += `\n\nValue: ${ context.activity.value }`;
                }

                await context.sendActivity(eocActivityMessage);

                // We are back at the host.
                await context.sendActivity('Back in the host bot.');

                await this.dialog.run(context, this.dialogState);
            }

            // By calling next() you ensure that the next BotHandler is run.
            await next();
        });

        this.onMembersAdded(async (context, next) => {
            const membersAdded = context.activity.membersAdded;
            for (let cnt = 0; cnt < membersAdded.length; ++cnt) {
                if (membersAdded[cnt].id !== context.activity.recipient.id) {
                    await context.sendActivity('Hello and welcome!');
                    await this.dialog.run(context, this.dialogState);
                }
            }

            // By calling next() you ensure that the next BotHandler is run.
            await next();
        });
    }

    async sendToSkill(context, targetSkill) {
        // NOTE: Always SaveChanges() before calling a skill so that any activity generated by the skill
        // will have access to current accurate state.
        await this.conversationState.saveChanges(context, true);

        // Route the activity to the skill
        const response = await this.skillClient.postToSkill(this.botId, targetSkill, this.skillsConfig.skillHostEndpoint, context.activity);

        // Check response status
        if (!(response.status >= 200 && response.status <= 299)) {
            throw new Error(`[HostBot]: Error invoking the skill id: "${ targetSkill.id }" at "${ targetSkill.skillEndpoint }" (status is ${ response.status }). \r\n ${ response.body }`);
        }
    }

    /**
     * Override the ActivityHandler.run() method to save state changes after the bot logic completes.
     */
    async run(context) {
        await super.run(context);

        // Save any state changes. The load happened during the execution of the Dialog.
        await this.conversationState.saveChanges(context, false);
    }
}

module.exports.HostBot = HostBot;
HostBot.ActiveSkillPropertyName = 'activeSkillProperty';
HostBot.DeliveryModePropertyName = 'deliveryModeProperty';
