yarnPath: .yarn/releases/yarn-berry-3.1.1.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"